"""
Synthesis Module
Generates enhanced question paper with improvements
"""

def generate_enhanced_paper(ast_data, report):
    enhanced_text = []
    enhanced_text.append("=" * 70)
    enhanced_text.append("ENHANCED QUESTION PAPER")
    enhanced_text.append("Generated by SmartExam Compiler")
    enhanced_text.append("=" * 70)
    enhanced_text.append("")
    syllabus = ast_data.get('syllabus', 'Unknown Subject')
    enhanced_text.append(f"Subject: {syllabus}")
    original_marks = ast_data.get('total_marks', 0)
    calculated_marks = report['statistics']['total_marks_calculated']
    if original_marks != calculated_marks:
        enhanced_text.append(f"Total Marks: {calculated_marks} (Corrected from {original_marks})")
    else:
        enhanced_text.append(f"Total Marks: {original_marks}")
    estimated_time = report['statistics']['estimated_time_minutes']
    enhanced_text.append(f"Time Allowed: {estimated_time} minutes")
    enhanced_text.append("")
    enhanced_text.append("-" * 70)
    enhanced_text.append("")
    enhanced_text.append("IMPROVEMENTS MADE:")
    enhanced_text.append("")
    for suggestion in report['suggestions']:
        enhanced_text.append(f"• {suggestion}")
    enhanced_text.append("")
    enhanced_text.append("-" * 70)
    enhanced_text.append("")
    enhanced_text.append("QUESTIONS:")
    enhanced_text.append("")
    questions = ast_data.get('questions', [])
    for i, q in enumerate(questions, 1):
        q_num = q.get('number', i)
        q_text = q.get('text', 'Question text')
        q_marks = q.get('marks', 0)
        q_difficulty = q.get('difficulty', 'MEDIUM')
        q_crispness = q.get('crispness', 'CRISP')
        improved_text, improved_marks = apply_improvements(
            q_text, q_marks, q_difficulty, q_crispness, report
        )
        enhanced_text.append(f"Q{q_num}. {improved_text}")
        enhanced_text.append(f"     [Marks: {improved_marks}] [Difficulty: {q_difficulty}]")
        enhanced_text.append("")
    enhanced_text.append("-" * 70)
    enhanced_text.append("")
    enhanced_text.append("DIFFICULTY DISTRIBUTION:")
    diff_check = report['checks']['difficulty_distribution']
    enhanced_text.append(f"  Easy:   {diff_check['easy_count']} questions ({diff_check['easy_percentage']}%)")
    enhanced_text.append(f"  Medium: {diff_check['medium_count']} questions ({diff_check['medium_percentage']}%)")
    enhanced_text.append(f"  Hard:   {diff_check['hard_count']} questions ({diff_check['hard_percentage']}%)")
    enhanced_text.append("")
    enhanced_text.append("QUALITY METRICS:")
    enhanced_text.append(f"  Overall Score: {report['crispness_score']}/100")
    enhanced_text.append(f"  Crispness: {report['checks']['crispness_analysis']['crispness_percentage']}%")
    enhanced_text.append("")
    enhanced_text.append("=" * 70)
    enhanced_text.append("End of Enhanced Question Paper")
    enhanced_text.append("=" * 70)
    return "\n".join(enhanced_text)

def apply_improvements(text, marks, difficulty, crispness, report):
    improved_text = text
    improved_marks = marks
    if crispness == 'VERBOSE':
        if len(text) > 100:
            improved_text = text[:100] + "... [Suggestion: Split into sub-questions or simplify]"
    if crispness == 'AMBIGUOUS':
        improved_text = text + " [Suggestion: Remove vague terms like 'etc', 'something']"
    if difficulty == 'EASY' and marks > 10:
        improved_marks = 10
        improved_text = text + f" [Marks adjusted: {marks} → {improved_marks}]"
    if difficulty == 'HARD' and marks < 10:
        improved_marks = 12
        improved_text = text + f" [Marks adjusted: {marks} → {improved_marks}]"
    return improved_text, improved_marks